### ISSUE TITLE
What is `typicode` folder in `todo-app` example?

### ISSUE THREAD

**Issue by Semigradsky** [feature-sliced/examples#4]
https://github.com/feature-sliced/examples/tree/master/todo-app/src/shared/api

**Comment by martis-git** [comment]
@Semigradsky Hello!

It's common used **jsontypicode mock-api server**
It was used in todo-app for simplifying tutorial and its implementation

https://jsonplaceholder.typicode.com/

**Comment by martis-git** [comment]
But it's good point to add some comments about it in files)

Thank you

**Comment by Semigradsky** [comment]
Thanks!
